name: Build and Deploy Youtube Clone to Azure Web App
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
   # strategy:
     # matrix:
      #  node-version: [12.x, 14.x, 16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Use Node.js ${{ matrix.node-version }}
       # uses: actions/setup-node@v2
        #with:
         # node-version: ${{ matrix.node-version }}
          #cache: 'npm'
      #- run: npm ci
      #- run: npm run build --if-present

      - name: Npm Install and Build
        run: |
          npm install
          npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:${{ github.sha }}
          file: Dockerfile
