name: Build and Deploy Youtube Clone to Azure Web App
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npx update-browserslist-db@latest
      - run: npm run build --if-present

     # - name: Zip artifact for deployment
      #  run: zip release.zip ./* -r
        
      #- name: Upload artifact for deployment job
       # uses: actions/upload-artifact@v3
        #with:
         # name: Build
          #path: release.zip
      - run: |
          zip app.zip build -r
          #zip -r app.zip . -i build/static/js/*.js
          #zip -r app.zip . -i build/static/css/*.css

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: app.zip
      

  release:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      #- name: Unzip artifact for deployment
       # run: unzip app.zip
      #- run: |
       #   unzip Build.zip
        #  rm Build.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.WEB_APP_NAME }}
          slot-name: 'Production'
          #images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:${{ github.sha }}
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          package: .

      #- name: Login to DockerHub
      #  uses: docker/login-action@v3
       # with:
        #  username: ${{ secrets.DOCKERHUB_USERNAME }}
         # password: ${{ secrets.DOCKERHUB_PASSWORD }}

     # - name: Build and Push Docker Image
       # uses: docker/build-push-action@v5
       # with:
       #   push: true
        #  tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:${{ github.sha }}
        #  file: Dockerfile

      
